# Generated by Django 5.2.11 on 2026-02-12 06:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_id', models.UUIDField(default=uuid.uuid4)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference_id'], name='transaction_referen_1bb812_idx'), models.Index(fields=['created_at'], name='transaction_created_67ce7b_idx'), models.Index(fields=['account'], name='transaction_account_36745c_idx')],
            },
        ),
    ]
